[package]
name = "compwaves"
version = "0.1.0"
edition = "2024"

[dependencies]
nannou = "0.19.0"
rosc = "0.11.3"
rodio = { version = "0.20", features = ["default"] }
nannou_audio = "0.19.0"
dotenvy = "0.15.7"
